oauthserver: http://localhost:9000/server
resource-server: http://localhost:7000/resource-note

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: note
      clientSecret: note
      scope: read,write
      auto-approve-scopes: '.*'
      accessTokenUri: ${oauthserver}/oauth/token
      userAuthorizationUri: ${oauthserver}/oauth/authorize
      authorizedGrantTypes: authorization_code
    resource:
      userInfoUri: ${oauthserver}/me
      tokenInfoUri: ${oauthserver}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG


server:
  port: 8000
  servlet:
    context-path: /client-note

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    jackson.time-zone: GMT+8

