oauthserver: http://localhost:8080/server
#
security:
  oauth2:
    client:
      clientId: photo
      clientSecret: photo
    resource:
      userInfoUri: ${oauthserver}/me
      tokenInfoUri: ${oauthserver}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG


server:
  port: 8081
  servlet:
    context-path: /resource