oauthserver: http://localhost:9000/server
#
security:
  oauth2:
    client:
      clientId: photo
      clientSecret: photo
    resource:
      userInfoUri: ${oauthserver}/me
      tokenInfoUri: ${oauthserver}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG


server:
  port: 7001
  servlet:
    context-path: /resource-photo